[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cosmicgate_sol = "FZLsE6xjkzrLc75VQHpwrrHgSeDZFvAUFqx33PdEevbC"

[programs.devnet]
cosmicgate_sol = "FZLsE6xjkzrLc75VQHpwrrHgSeDZFvAUFqx33PdEevbC"

[programs.mainnet]
cosmicgate_sol = "FZLsE6xjkzrLc75VQHpwrrHgSeDZFvAUFqx33PdEevbC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
